apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Some normal resources that are not encrypted
  - deployment.yaml
  - service.yaml

generators:
  # Reference the ksops plugin configuration
  - ksops-config.yaml